# Generated by Django 5.0.6 on 2024-05-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_like_created_at_like_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpost',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
