# Generated by Django 5.0.6 on 2024-05-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_textpost_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='created_at',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='comment_like',
            field=models.BooleanField(default=False),
        ),
    ]
