# Generated by Django 5.0.6 on 2024-05-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_customuser_followers_customuser_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
