# Generated by Django 5.0.6 on 2024-05-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
